"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { ArrowDown, ArrowUpRight, MapPin, Volume2, VolumeX, Soup, Gem, BellRing, Amphora, Utensils, X, Menu } from "lucide-react";

const maps = "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent("T.M.A Marriage Hall Thirukarakavur Papanasam Tamil Nadu 614302");
const target = new Date("2026-10-25T10:30:00+05:30").getTime();
const events = [
 {day:"24 OCTOBER · SATURDAY", name:"Haldi", tamil:"நலங்கு", time:"03:00 PM", description:"A joyful beginning filled with turmeric, laughter and blessings.", Icon:Soup},
 {day:"24 OCTOBER · SATURDAY", name:"Engagement", tamil:"நிச்சயதார்த்தம்", time:"06:00 PM", description:"The moment we officially begin our forever.", Icon:Gem},
 {day:"24 OCTOBER · SATURDAY", name:"Reception", tamil:"வரவேற்பு", time:"07:00 PM ONWARDS", description:"Dinner, celebration and memories with the people we love.", Icon:Utensils},
 {day:"25 OCTOBER · SUNDAY", name:"Marriage / Muhurtham", tamil:"திருமணம்", time:"10:30 AM – 11:00 AM", description:"With sacred vows and your blessings, our new chapter begins.", Icon:Amphora},
];
function Kolam({className=""}:{className?:string}) {return <svg aria-hidden="true" viewBox="0 0 100 100" className={"kolam "+className}><g fill="none" stroke="currentColor" strokeWidth="1"><path d="M50 5C10 35 10 65 50 95C90 65 90 35 50 5ZM5 50C35 10 65 10 95 50C65 90 35 90 5 50Z"/><path d="M50 19 81 50 50 81 19 50ZM50 31 69 50 50 69 31 50Z"/>{[30,50,70].map(x=>[30,50,70].map(y=><circle key={x+":"+y} cx={x} cy={y} r="1.5" fill="currentColor"/>))}</g></svg>}
function Reveal({children,className=""}:{children:ReactNode;className?:string}) {const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:28,scale:.98}} whileInView={{opacity:1,y:0,scale:1}} viewport={{once:true,amount:.12}} transition={{duration:.9,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Countdown(){const [left,setLeft]=useState<number|null>(null);useEffect(()=>{const update=()=>setLeft(Math.max(0,target-Date.now()));update();const timer=setInterval(update,1000);return()=>clearInterval(timer)},[]);const nums=left===null?["—","—","—","—"]:[Math.floor(left/86400000),Math.floor(left/3600000)%24,Math.floor(left/60000)%60,Math.floor(left/1000)%60].map(n=>String(n).padStart(2,"0"));return <section className="countdown"><Reveal><p className="eyebrow">EVERY MOMENT BRINGS US CLOSER</p><h2>{left===0?"Our forever has begun.":'Until we say “I do”'}</h2><div className="clock" role="timer" aria-label="Time until the wedding">{nums.map((n,i)=><div key={i}><strong>{n}</strong><span>{["DAYS","HOURS","MINUTES","SECONDS"][i]}</span></div>)}</div><p className="time-note">25 October 2026 · 10:30 AM IST</p></Reveal></section>}
export default function Home(){
 const reduced=useReducedMotion();const [opened,setOpened]=useState(false);const [menu,setMenu]=useState(false);const [music,setMusic]=useState(false);const audio=useRef<AudioContext|null>(null);const notes=useRef<OscillatorNode[]>([]);const hero=useRef<HTMLElement>(null);const reveal=useRef<HTMLElement>(null);
 const {scrollYProgress}=useScroll({target:hero,offset:["start start","end start"]});const imageY=useTransform(scrollYProgress,[0,1],[0,reduced?0:90]);
 const {scrollYProgress:doorProgress}=useScroll({target:reveal,offset:["start end","center center"]});const leftDoor=useTransform(doorProgress,[0,1],["0%",reduced?"-100%":"-100%"]);const rightDoor=useTransform(doorProgress,[0,1],["0%","100%"]);
 useEffect(()=>{document.body.style.overflow=opened?"":"hidden";return()=>{document.body.style.overflow=""}},[opened]);
 useEffect(()=>()=>{audio.current?.close()},[]);
 const toggleMusic=async()=>{if(music){await audio.current?.suspend();setMusic(false);return}if(!audio.current || audio.current.state === "closed"){const ctx=new AudioContext();audio.current=ctx;const gain=ctx.createGain();gain.gain.value=.022;gain.connect(ctx.destination);[130.81,196,261.63,329.63].forEach((freq,i)=>{const osc=ctx.createOscillator();osc.type="sine";osc.frequency.value=freq;osc.detune.value=i%2?2:-2;osc.connect(gain);osc.start();notes.current.push(osc)})}await audio.current.resume();setMusic(true)};
 return <>
 <AnimatePresence>{!opened&&<motion.div className="invitation-cover" role="dialog" aria-modal="true" aria-label="Open Karthik and Sandhya’s wedding invitation" exit={{opacity:0,transition:{delay:reduced?0:.55,duration:.55}}}><motion.div className="cover-half cover-left" exit={{x:"-100%"}} transition={{duration:reduced?0:1.2,ease:[.76,0,.24,1]}}/><motion.div className="cover-half cover-right" exit={{x:"100%"}} transition={{duration:reduced?0:1.2,ease:[.76,0,.24,1]}}/><motion.div className="cover-content" exit={{opacity:0,y:-15}} transition={{duration:.3}}><p className="eyebrow">AN INVITATION TO OUR FOREVER</p><Kolam/><p className="cover-monogram">K <i>&</i> S</p><p className="cover-date">24 & 25 OCTOBER 2026</p><button autoFocus onClick={()=>setOpened(true)} className="button light">Open invitation <ArrowUpRight size={17}/></button><p className="cover-foot">WITH LOVE, KARTHIK & SANDHYA</p></motion.div></motion.div>}</AnimatePresence>
 <div inert={!opened}>
 <nav><a className="monogram" href="#home" aria-label="Karthik and Sandhya home">K <i>♥</i> S</a><div className="desktop-links">{["Our Story","Events","Venue","Gallery"].map((n,i)=><a key={n} href={"#"+["story","events","venue","gallery"][i]}>{n}</a>)}</div><a className="nav-cta" href={maps} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={15}/></a><button className="menu-button" aria-label={menu?"Close menu":"Open menu"} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
 {menu&&<div className="mobile-links">{["Our Story","Events","Venue","Gallery"].map((n,i)=><a onClick={()=>setMenu(false)} key={n} href={"#"+["story","events","venue","gallery"][i]}>{n}</a>)}</div>}
 <main><section id="home" className="hero" ref={hero}><div className="hero-copy"><motion.div className="hero-ornament" animate={reduced?{}:{rotate:[-2,2,-2]}} transition={{repeat:Infinity,duration:9}}><BellRing size={24} strokeWidth={1}/></motion.div><p className="tamil invocation" lang="ta">॥ ஸ்ரீ கிருஷ்ணாய நம ॥</p><p className="eyebrow">WITH LOVE & THE BLESSINGS OF OUR FAMILIES</p><h1>Karthik<span>&</span>Sandhya</h1><div className="hero-date"><strong>24 — 25</strong><span>OCTOBER 2026</span></div><p className="hero-place">THIRUKARAKAVUR · TAMIL NADU</p><a href="#temple" className="scroll-link">Scroll to celebrate with us <ArrowDown size={18}/></a></div><div className="hero-image"><motion.img style={{y:imageY}} src="/temple-doorway.webp" alt="Sunlit Tamil temple framed by carved pillars, brass bells and jasmine" fetchPriority="high" width="1024" height="1536"/><div className="image-caption">A beautiful beginning.<span lang="ta" className="tamil">கார்த்திக் & சந்தியா</span></div><span className="photo-corner">24.10.26 — 25.10.26</span></div><div className="hero-bell-right" aria-hidden="true"><BellRing size={22} strokeWidth={1}/></div><span className="side-note">TWO HEARTS · TWO FAMILIES · ONE FOREVER</span></section>
 <section id="temple" className="temple-reveal" ref={reveal}><img src="/temple-doorway.webp" loading="lazy" alt="A golden gopuram beyond a traditional temple entrance"/><div className="temple-shade"/><motion.div className="temple-door left" style={{x:leftDoor}}/><motion.div className="temple-door right" style={{x:rightDoor}}/><div className="temple-words"><Kolam/><p className="eyebrow">A SACRED PROMISE. A LIFETIME OF LOVE.</p><h2>Some beginnings<br/>are written in <em>the stars.</em></h2></div></section>
 <section id="story" className="story"><Reveal className="section-intro"><p className="eyebrow">01 / OUR BEAUTIFUL BEGINNING</p><h2>Two hearts.<br/>Two families.<br/><em>One beautiful beginning.</em></h2></Reveal><Reveal className="couple-composition"><span className="vertical-caption">TOGETHER IS A BEAUTIFUL PLACE TO BE</span><div className="couple-photo"><img src="/invitation.jpg" alt="Karthik and Sandhya, from their wedding invitation" loading="lazy" width="900" height="1600"/></div><Kolam className="couple-kolam"/><div className="couple-signature"><span>Karthik G</span><i>&</i><span>Sandhya S</span></div><p className="couple-caption">Together with our families, we invite you to celebrate<br className="desktop-break"/> the beginning of our forever.</p></Reveal></section>
 <section className="save-date"><Reveal><p className="eyebrow">SAVE THE DATE</p><div className="date-numbers"><span>24</span><i>&</i><span>25</span></div><div className="date-bottom"><span>OCTOBER</span><Kolam/><span>2026</span></div><p>Two days of love, laughter and a lifetime of memories.</p></Reveal></section>
 <section id="events" className="events"><Reveal className="section-intro"><p className="eyebrow">02 / THE CELEBRATIONS</p><h2>Our wedding<br/><em>celebrations.</em></h2><p className="section-subtitle">Come for the moments. Stay for the memories.</p></Reveal><div className="timeline">{events.map(({day,name,tamil,time,description,Icon},i)=><Reveal key={name} className={"event event-"+i}><span className="timeline-node"/><div className="event-inner"><div className="event-top"><Icon strokeWidth={1} size={32}/><span className="event-number">0{i+1}</span></div><p className="eyebrow event-day">{day}</p><span className="event-tamil tamil" lang="ta">{tamil}</span><h3>{name}</h3><p className="event-time">{time}</p><p className="event-description">{description}</p></div></Reveal>)}</div><p className="all-events"><MapPin size={15}/> All celebrations at T.M.A Marriage Hall · Times in IST</p></section>
 <section className="muhurtham"><div className="muhurtham-image"><img src="/jasmine-lamp-still-life.webp" alt="A traditional brass lamp surrounded by fresh jasmine and maroon silk" loading="lazy"/></div><Reveal className="muhurtham-copy"><Kolam/><p className="eyebrow">THE SACRED MOMENT</p><h2>The Muhurtham</h2><p className="tamil" lang="ta">மாங்கல்யம் தந்துனானேன</p><div className="sacred-line"/><p className="muhurtham-date">25 OCTOBER 2026 · SUNDAY</p><div className="muhurtham-time"><span>10:30 <small>AM</small></span><i>—</i><span>11:00 <small>AM</small></span></div><Amphora className="kalasam" size={52} strokeWidth={1}/><p>A sacred promise, surrounded by love.<br/>Your presence will make it complete.</p></Reveal></section>
 <section id="venue" className="venue"><Reveal className="venue-copy"><p className="eyebrow">03 / THE PLACE</p><h2>Where we<br/>begin <em>forever.</em></h2><div className="venue-address"><p className="venue-name">T.M.A Marriage Hall</p><p>Thirukarakavur, Papanasam,<br/>Tamil Nadu – 614302</p></div><a className="button" href={maps} target="_blank" rel="noreferrer"><MapPin size={17}/> Open in Google Maps <ArrowUpRight size={17}/></a><p className="map-note">Find your route and travel time in Google Maps.</p></Reveal><Reveal className="map-stationery"><div className="stationery-top"><span>YOU’RE INVITED</span><Kolam/></div><iframe title="Map of T.M.A Marriage Hall in Thirukarakavur, Papanasam" src={"https://maps.google.com/maps?q="+encodeURIComponent("T.M.A Marriage Hall Thirukarakavur Papanasam Tamil Nadu 614302")+"&output=embed"} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><div className="stationery-bottom"><span>T.M.A MARRIAGE HALL</span><a href={maps} target="_blank" rel="noreferrer" aria-label="Get directions to the wedding venue"><ArrowUpRight size={23}/></a></div></Reveal></section>
 <Countdown/>
 <section id="gallery" className="gallery"><Reveal className="gallery-heading"><div><p className="eyebrow">04 / LITTLE MOMENTS, LASTING MEMORIES</p><h2>A little glimpse<br/>of <em>our world.</em></h2></div><p>The faces, the traditions,<br/>the feeling of coming home.</p></Reveal><div className="gallery-track"><Reveal className="gallery-item gallery-portrait"><div className="couple-photo"><img src="/invitation.jpg" alt="Karthik and Sandhya together" loading="lazy"/></div><p><span>01</span> The beginning of us</p></Reveal><Reveal className="gallery-item gallery-lamp"><img src="/jasmine-lamp-still-life.webp" alt="Jasmine, silk and the warm glow of a brass lamp" loading="lazy"/><p><span>02</span> Rooted in tradition</p></Reveal><Reveal className="gallery-item gallery-ceremony"><div className="ceremony-photo"><img src="/invitation.jpg" alt="Wedding ceremony artwork from the couple’s invitation" loading="lazy"/></div><p><span>03</span> A promise of forever</p></Reveal></div></section>
 <section className="blessings"><Reveal><Kolam/><p className="eyebrow">WITH YOUR LOVE & BLESSINGS</p><p className="blessing-tamil tamil" lang="ta">தங்கள் வருகை எங்கள் வாழ்வின்<br/>இனிய தொடக்கத்திற்கு<br/>ஆசீர்வாதமாக அமையும்.</p><p className="blessing-english">Your gracious presence will be a blessing<br/>as we begin our new chapter together.</p><div className="blessing-divider"/></Reveal></section>
 <footer><img className="footer-image" src="/temple-doorway.webp" alt="" loading="lazy"/><div className="footer-shade"/><Reveal className="footer-content"><p className="eyebrow">THE BEGINNING OF A LIFETIME</p><h2>Karthik <i>&</i> Sandhya</h2><p className="footer-date">24 & 25 OCTOBER 2026</p><p className="footer-message">We can’t wait to celebrate with you.</p><p>T.M.A Marriage Hall<br/>Thirukarakavur, Papanasam</p><a className="button light" href={maps} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={17}/></a><Kolam/><div className="footer-bottom"><span>MADE WITH LOVE, FOR OUR LOVED ONES</span><a href="#home">BACK TO TOP ↑</a></div></Reveal></footer>
 </main><button className="music-toggle" onClick={toggleMusic} aria-pressed={music} aria-label={music?"Mute ambient music":"Play ambient music"}>{music?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{music?"SOUND ON":"SOUND OFF"}</span></button>
 </div></>;
}
